---
name: Update (or add) package to Hex repository
on:
  workflow_call:
    inputs:
      hex_repo_name:
        description: Shortname for the Hex repository
        type: string
        required: true
      hex_git_repo:
        description: The GitHub repository to commit the package to. (Formatted as "org/repo".)
        type: string
        required: true
      hex_domain:
        description: Domain name of the deployed Hex repository
        type: string
        required: true
      hex_port:
        description: Port the Hex repository listens on
        type: number
        required: true
    secrets:
      HEX_REPO_GHACTIONS_USER:
        description: The HTTP Basic Auth user given access to the Hex repository
        required: true
      HEX_REPO_GHACTIONS_PASSWORD:
        description: Password for the Hex repository user
        required: true
      HEX_TOKEN:
        description: Personal access token to checkout the hex_git_repo
        required: true

jobs:
  build_package:
    name: Build Package
    runs-on: ubuntu-latest
    env:
      HEX_PRIVATE_KEY: ${{ secrets.HEX_PRIVATE_KEY }}
    steps:
      - name: Install BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: '24.1.6'
          elixir-version: '1.13.3'
      - name: Checkout lib
        uses: actions/checkout@v3
        with:
          path: library
      - name: Cache lib deps
        uses: actions/cache@v3
        env:
          cache-name: mix-deps
        with:
          path: library/deps
          key: ${{ runner.os }}-${{ github.repository }}-build-${{ env.cache-name }}-${{ hashFiles('library/**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.repository }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-${{ github.repository }}-build-
            ${{ runner.os }}-${{ github.repository }}-
      - name: Checkout Hex repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.hex_git_repo }}
          token: ${{ secrets.HEX_TOKEN }}
          path: hex_repo
      - name: Add Hex repo to Mix
        run: |
          mix hex.repo add ${{ inputs.hex_repo_name }} \
            https://${{ secrets.HEX_REPO_GHACTIONS_USER }}:${{ secrets.HEX_REPO_GHACTIONS_PASSWORD }}@${{ inputs.hex_domain }}:${{ inputs.hex_port }} \
            --public-key=hex_repo/public/public_key
      - name: Do build
        run: |
          cd library
          OUT=$(mix hex.build | tail -n 1 | cut -d ' ' -s -f 3)
          mv $OUT ${{ github.workspace }}/hex_repo/public/tarballs/
      - name: Update repo
        run: |
          cd hex_repo
          echo $HEX_PRIVATE_KEY > private_key.pem
          mix hex.registry build public --name=${{ inputs.hex_repo_name }} --private-key=private_key.pem
          git config user.name github-actions
          git config user.email github-actions@${{ inputs.hex_domain }}
          git add public
          git commit -m "Rebuilt registry"
          git push
